apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv2-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/my-pv2-volume"
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-namespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: my-pvc2-volume
  namespace: mysql-namespace
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: mysql-namespace
  labels:
    app: phpmyadmin-mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-mysql-app
  template:
    metadata:
      labels:
        app: phpmyadmin-mysql-app
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql          
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "my-password"            
            - name: MYSQL_DATABASE
              value: "my-database"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: my-pvc2-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: phpmyadmin-mysql-app
  namespace: mysql-namespace
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    name: mysql-port
  selector:
    app: phpmyadmin-mysql-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql-namespace
  labels:
    app: phpmyadmin-mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-mysql-app
  template:
    metadata:
      labels:
        app: phpmyadmin-mysql-app
    spec:
      containers:        
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:5.1.0
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: "mysql-service"
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: "root"
            - name: PMA_PASSWORD
              value: "my-password"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-mysql-app
  namespace: mysql-namespace
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: phpmyadmin-port
  selector:
    app: phpmyadmin-mysql-app